# Generated by Django 5.1 on 2024-09-25 10:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Cuisine', 'Cuisine'), ('Toilette', 'Toilette'), ('Moto', 'Moto')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_creation', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mensuel', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('tel', models.CharField(default='+261', max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('date_embauche', models.DateTimeField(default=django.utils.timezone.now)),
                ('sexe', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default='T', max_length=5)),
                ('date_naissance', models.DateField()),
                ('photo', models.ImageField(blank=True, default='photos/pdp_defaut.png', upload_to='photos/')),
                ('adresse', models.CharField(max_length=100, null=True)),
                ('type_personnel', models.CharField(choices=[('Salarié', 'Salarié'), ('Bénévole', 'Bénévole'), ('Freelance', 'Freelance'), ('Stagiaire', 'Stagiaire')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdp', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OperationEntrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=0, default=5000, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('date_transaction', models.DateField(default=django.utils.timezone.now)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caisse.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='OperationSortir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('date_de_sortie', models.DateField(default=django.utils.timezone.now)),
                ('quantité', models.DecimalField(decimal_places=0, default=1, max_digits=10)),
                ('Categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caisse.categorie')),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caisse.beneficiaire')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caisse.fournisseur')),
            ],
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='personnel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caisse.personnel'),
        ),
    ]
