# Generated by Django 5.1.1 on 2024-09-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationsortir',
            name='montant',
            field=models.DecimalField(decimal_places=0, default=500, max_digits=10),
        ),
    ]
