# Generated by Django 5.1.1 on 2024-09-30 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0002_alter_operationsortir_montant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operationsortir',
            old_name='Categorie',
            new_name='categorie',
        ),
    ]
